# Generated by Django 4.2.1 on 2023-07-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='new_answers_count',
            field=models.IntegerField(default=0, verbose_name='new answers count'),
        ),
    ]
