# Generated by Django 4.2.1 on 2023-07-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_light_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ia_ai',
            field=models.BooleanField(default=False),
        ),
    ]
