# Generated by Django 4.2.1 on 2023-07-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_ia_ai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ia_ai',
            new_name='is_ai',
        ),
    ]
